### ISSUE TITLE
Silverstrand location info

### ISSUE THREAD

**Issue by sthallor** [lorenz-g/tesla-megapack-tracker#14]
From this website:  https://beiconstruction.com/expanding-energy-storage-resources-with-tesla-megapacks/
BEI construction indicates Silverstrand (11MW, 15 Megapacks, operator is Able Grid) the location is Camarillo, CA.

**Comment by lorenz-g** [comment]
Hi, really sorry for the late reply but thanks for sharing the link. 

I have added your info and you can see it here:
https://lorenz-g.github.io/tesla-megapack-tracker/projects/193.html
