### ISSUE TITLE
Tesla mega pack in africa

### ISSUE THREAD

**Issue by chrisrama** [lorenz-g/tesla-megapack-tracker#2]
Here I found another Tesla project of power pack that was install this year in February. It now operational. I think you might add it to. Here some the link to it
[Tesmanian report](https://www.tesmanian.com/blogs/tesmanian-blog/tesla-powerpack-2-26-mwh-installed-in-abuja-nigeria-to-cut-expenditure-and-reduce-dependence-on-diesel)

[Teslarati report](https://www.teslarati.com/tesla-power-pack-nigeria-vs-diesel-generators/)

**Comment by lorenz-g** [comment]
Hi Chris, thanks for pointing this out. 

I have added the project the the list of "small" powerpack installations. 
For now I am not adding powerpack projects of less than 5MWh to the map, but that might change in the future.
