### ISSUE TITLE
Make tables sortable and filterable

### ISSUE THREAD

**Issue by EwoutH** [lorenz-g/tesla-megapack-tracker#6]
First of all, thanks for this great tracker!

It would be very useful if the tables were sortable (on MWh for example) and filterable (on status). Do you think adding that would be possible?

**Edit:** I reloaded my browser and now they are sortable! Could this be a bug?

Filterable would still be a great addition!

**Comment by lorenz-g** [comment]
Hi, thanks for the comment. 
I saw you edited you comment :) 

Searching and sorting should be possible. 
The search bar takes a while until it shows up. I am mostly testing with Firefox... 

![Pasted_Image_08_10_2022__17_55](https://user-images.githubusercontent.com/4258655/194716394-de1d8a87-e870-47a4-a326-1027e6c74341.png)
